title: SnookaGames
description: Play free online games at SnookaGames. Browse and enjoy a huge collection of fun games.
baseurl: ""
url: "https://snookagames.github.io"
theme: minima

collections:
  games:
    output: true
    permalink: /games/:name/
